### ISSUE TITLE
5.4.0精简版打包报错

### ISSUE THREAD

**Issue by ddoplayer2012** [pure-admin/vue-pure-admin#1099]
### 描述问题 (Describe the problem)

F:\pure-admin-thin> pnpm  run build

> pure-admin-thin@5.4.0 build F:\pure-admin-thin
> rimraf dist && NODE_OPTIONS=--max-old-space-size=8192 vite build

vite v5.2.10 building for production...
╭───────────────────────────────────────────────╮
│ 您好! 欢迎使用 pure-admin 开源项目            │
│ 我们为您精心准备了下面两个贴心的保姆级文档    │
│ https://yiming_chang.gitee.io/pure-admin-doc  │
│ https://pure-admin-utils.netlify.app          │
╰───────────────────────────────────────────────╯
✓ 21 modules transformed.
error during build:
RollupError: Expression expected
    at getRollupError (file:///F:/pure-admin-thin/node_modules/.pnpm/rollup@4.16.2/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at ParseError.initialise (file:///F/pure-admin-thin/node_modules/.pnpm/rollup@4.16.2/node_modules/rollup/dist/es/shared/node-entry.js:11380:28)
    at convertNode (file:///F:/pure-admin-thin/node_modules/.pnpm/rollup@4.16.2/node_modules/rollup/dist/es/shared/no    at convertProgram (file:///F:/pure-admin-thin/node_modules/.pnpm/rollup@4.16.2/node_modules/rollup/dist/es/shared/node-entry.js:12451:12)
    at Module.setSource (file:///F:/pure-admin-thin/node_modules/.pnpm/rollup@4.16.2/node_modules/rollup/dist/es/shared/node-entry.js:14295:24)
    at async ModuleLoader.addModuleSource (file:///F:/pure-admin-thin/node_modules/.pnpm/rollup@4.16.2/node_modules/rollup/dist/es/shared/node-entry.js:18948:13)

### 如何复现该问题 (How to reproduce the problem)

node  v20.12.2

### 操作系统和浏览器信息 (Operating system and browser information)

node  v20.12.2    windows10

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
<img width="1081" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/8c7a044e-bb97-4c67-9e22-7980084cca3d">
