### ISSUE TITLE
精简版，点击内容全屏报错

### ISSUE THREAD

**Issue by zphtown** [pure-admin/vue-pure-admin#488]
Uncaught RangeError: Maximum call stack size exceeded
    at toRaw (reactivity.esm-bundler.js:991:29)
    at Proxy.hasOwnProperty2 (reactivity.esm-bundler.js:457:17)

今天刚下的精简版

**Comment by duliang123** [comment]
我今天测试也是

**Comment by Diamond-zh** [comment]
找到CHANGE_SETTING方法，修改为if(Object.prototype.hasOwnProperty.call(this, key)){
        this[key] = value;
      }
