### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by WB967** [pure-admin/vue-pure-admin#789]
### 描述问题 (Describe the problem)

大佬你好，在今早我拉取并运行了代码，运行正常。
下午拉取了最新代码，重新安装了依赖，运行正常，但是登录时，退报错并导致运行结束。
回滚之五天前的代码，重新安装依赖后，又可以正常运行（登录）

### 如何复现该问题 (How to reproduce the problem)

file:///C:/Users/XXX/Desktop/%E5%AE%98%E6%96%B9%E7%A4%BA%E4%BE%8B/vue-pure-admin/node_modules/.pnpm/vite-plugin-fake-server@2.0.0/node_modules/vite-plugin-fake-server/dist/index.mjs:661
                                responseHeaders: new Headers({ ...globalResponseHeaders, ...responseHeaders }),
                                                     ^

ReferenceError: Headers is not defined
    at getResponse (file:///C:/Users/XXX/Desktop/%E5%AE%98%E6%96%B9%E7%A4%BA%E4%BE%8B/vue-pure-admin/node_modules/.pnpm/vite-plugin-fake-server@2.0.0/node_modules/vite-plugin-fake-server/dist/index.mjs:661:26)
    at middleware (file:///C:/Users/XXX/Desktop/%E5%AE%98%E6%96%B9%E7%A4%BA%E4%BE%8B/vue-pure-admin/node_modules/.pnpm/vite-plugin-fake-server@2.0.0/node_modules/vite-plugin-fake-server/dist/index.mjs:678:34)
    at call (file:///C:/Users/XXX/Desktop/%E5%AE%98%E6%96%B9%E7%A4%BA%E4%BE%8B/vue-pure-admin/node_modules/.pnpm/vite@5.0.0-beta.17_@types+node@20.9.0_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-3p9Yqpeo.js:42846:7)
    at next (file:///C:/Users/XXX/Desktop/%E5%AE%98%E6%96%B9%E7%A4%BA%E4%BE%8B/vue-pure-admin/node_modules/.pnpm/vite@5.0.0-beta.17_@types+node@20.9.0_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-3p9Yqpeo.js:42790:5)
    at Function.handle (file:///C:/Users/XXX/Desktop/%E5%AE%98%E6%96%B9%E7%A4%BA%E4%BE%8B/vue-pure-admin/node_modules/.pnpm/vite@5.0.0-beta.17_@types+node@20.9.0_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-3p9Yqpeo.js:42793:3)
    at Server.app (file:///C:/Users/XXX/Desktop/%E5%AE%98%E6%96%B9%E7%A4%BA%E4%BE%8B/vue-pure-admin/node_modules/.pnpm/vite@5.0.0-beta.17_@types+node@20.9.0_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-3p9Yqpeo.js:42658:37)
    at Server.emit (node:events:513:28)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
 ELIFECYCLE  Command failed with exit code 1.

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by WB967** [comment]
我记得错误是index.mjs中的new Headers()报错的

**Comment by xiaoxian521** [comment]
最新版代码有node版本和pnpm版本要求 具体看提交记录

**Comment by xioashuang** [comment]
TypeError: Cannot read properties of undefined (reading 'color')

**Comment by xioashuang** [comment]
![截图](https://github.com/pure-admin/vue-pure-admin/assets/127270093/360d4d80-c178-41fe-8bbc-31813b8fe877)
