### ISSUE TITLE
pnpm dev 怎么跑都跑不起来

### ISSUE THREAD

**Issue by jg-8** [pure-admin/vue-pure-admin#800]
### 描述问题 (Describe the problem)

node 16.18.1
node 18.18.2
node 19.9.0
node 14.20.1
这些版本都试过
pnpm install 后，serve 怎么都是报错
pnpm serve

pure-admin-thin@4.4.0 serve /web/boot-admin-ui
pnpm dev

pure-admin-thin@4.4.0 dev /web/boot-admin-ui
NODE_OPTIONS=--max-old-space-size=4096 vite

failed to load config from /web/boot-admin-ui/vite.config.ts
error when starting dev server:
TypeError: (0 , import_theme.default) is not a function
at getPluginsList (/web/boot-admin-ui/vite.config.ts:515:30)
at vite_config_default (/web/boot-admin-ui/vite.config.ts:593:14)
at loadConfigFromFile (file:///web/boot-admin-ui/node_modules/.pnpm/vite@[4.5.0_@types](mailto:4.5.0_@types)+node@20.9.1_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66174:15)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async resolveConfig (file:///web/boot-admin-ui/node_modules/.pnpm/vite@[4.5.0_@types](mailto:4.5.0_@types)+node@20.9.1_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65767:28)
at async createServer (file:///web/boot-admin-ui/node_modules/.pnpm/vite@4.5.0https://github.com/types+node@20.9.1_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65044:20)
at async CAC. (file:///web/boot-admin-ui/node_modules/.pnpm/vite@[4.5.0_@types](mailto:4.5.0_@types)+node@20.9.1_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/cli.js:763:24)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### 如何复现该问题 (How to reproduce the problem)

pnpm i 正常
pnpm dev 都不行，报一样的错误

### 操作系统和浏览器信息 (Operating system and browser information)

在 macOS 上，各种版本的 node 都试过

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by jg-8** [comment]
无效也说明下原因嘛，确实一直跑不起来
