### ISSUE TITLE
在精简版接口请求拿到数据后调用useECharts报错

### ISSUE THREAD

**Issue by lqllife** [pure-admin/vue-pure-admin#832]
### 描述问题 (Describe the problem)

这个问题是基于 #803 ，经测试发现，这个报错
```
TypeError: Cannot destructure property 'appContext' of '(0 , a.getCurrentInstance)(...)' as it is null.
    at Ct (index.mjs:3:23710)
    at Kr (index.mjs:3:23866)
    at hook.ts:98:30
    at Proxy.forEach (<anonymous>)
    at initEcharts (hook.ts:96:20)
    at onSearch (hook.ts:82:7)
```
是因为在异步请求之后，`getCurrentInstance()`的值始终为null，导致的这个报错。
参考文章：
https://juejin.cn/post/6918365587248775175

### 如何复现该问题 (How to reproduce the problem)

```ts
async function onSearch() {
    console.log(getCurrentInstance()); // 值是正常的
    loading.value = true;
    try {
      const { collections, total_num, page_size } = await VoiceSummaryApi.agent(
        toRaw(form)
      );
      console.log(getCurrentInstance()); // 值是 null
      dataList.value = collections;
      pagination.total = total_num;
      pagination.pageSize = page_size;
      dataList.value.forEach((_, i) => {
        console.log(templateRef(`PieChartRef${i}`) as Ref<HTMLDivElement>);
        const { setOptions } = useECharts(
          templateRef(`PieChartRef${i}`) as Ref<HTMLDivElement>,
          { theme }
        );
        //setOptions(
        //  {
        //    tooltip: {
        //      trigger: "item",
        //      confine: true
        //    },
        //    series: [
        //      {
        //        name: "Github信息",
        //        type: "pie",
        //        // center: ["30%", "50%"],
        //        data: [
        //          { value: 1067, name: "watchers" },
        //          { value: 4037, name: "star" },
        //          { value: 859, name: "forks" }
        //        ],
        //        emphasis: {
        //          itemStyle: {
        //            shadowBlur: 10,
        //            shadowOffsetX: 0,
        //            shadowColor: "rgba(0, 0, 0, 0.5)"
        //          }
        //        }
        //      }
        //    ]
        //  },
        //  {
        //    name: "click",
        //    callback: ({ data: { name, value } }) => {
        //      console.log(
        //        `您点击了第 ${
        //          i + 1
        //        } 行，图表标题为${name}，图表数据为：${value}`
        //      );
        //    }
        //  }
        //);
      });
      setTimeout(() => {
        loading.value = false;
      }, 200);
    } catch (e) {
      console.log(e);
      setTimeout(() => {
        loading.value = false;
      }, 200);
    }
  }
```

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://pure-admin-utils.netlify.app/hooks/useEcharts/useEcharts#%E4%BD%BF%E7%94%A8%E5%89%8D%E6%8F%90
