### ISSUE TITLE
@pureadmin/theme插件使用报错

### ISSUE THREAD

**Issue by yixingruohuo** [pure-admin/vue-pure-admin#852]
### 描述问题 (Describe the problem)

项目安装完依赖之后运行报错，报错信息定位在@pureadmin/theme插件的使用上，把这个插件换成@zougt/vite-plugin-theme-preprocessor，项目就可以正常运行。
报错信息如下：
pnpm dev
> pure-admin-thin@4.5.0 dev D:\projects\vue3\pure-admin-thin
> NODE_OPTIONS=--max-old-space-size=4096 vite
failed to load config from D:\projects\vue3\pure-admin-thin\vite.config.ts
error when starting dev server:
TypeError: (0 , import_theme.default) is not a function
    at getPluginsList (D:\projects\vue3\pure-admin-thin\vite.config.ts:511:30)
    at vite_config_default (D:\projects\vue3\pure-admin-thin\vite.config.ts:596:14)
    at loadConfigFromFile (file:///D:/projects/vue3/pure-admin-thin/node_modules/.pnpm/vite@4.5.1_@types+node@20.10.6_sass@1.69.7_terser@5.26.0/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66181:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (file:///D:/projects/vue3/pure-admin-thin/node_modules/.pnpm/vite@4.5.1_@types+node@20.10.6_sass@1.69.7_terser@5.26.0/node_modules/vite/dist/node/chunks/dep-68d1a114.js:65774:28)
    at async _createServer (file:///D:/projects/vue3/pure-admin-thin/node_modules/.pnpm/vite@4.5.1_@types+node@20.10.6_sass@1.69.7_terser@5.26.0/node_modules/vite/dist/node/chunks/dep-68d1a114.js:65051:20)
    at async CAC.<anonymous> (file:///D:/projects/vue3/pure-admin-thin/node_modules/.pnpm/vite@4.5.1_@types+node@20.10.6_sass@1.69.7_terser@5.26.0/node_modules/vite/dist/node/cli.js:763:24)
 ELIFECYCLE  Command failed with exit code 1.
![1](https://github.com/pure-admin/vue-pure-admin/assets/30967409/fe993e89-2bd0-49a6-a688-5507d3dabab8)

### 如何复现该问题 (How to reproduce the problem)

第一次拉下来项目代码，pnpm安装依赖，运行项目就可看到报错，项目运行不起来。

### 操作系统和浏览器信息 (Operating system and browser information)

win10系统
谷歌浏览器
node版本：v19.0.1
npm版本：8.19.2
pnpm版本：8.14.0

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
node版本问题 看https://github.com/pure-admin/vue-pure-admin/pull/738 多看平台使用要求
