### ISSUE TITLE
build时包 (0 , import_theme.default) is not a function错误

### ISSUE THREAD

**Issue by ggwork** [pure-admin/vue-pure-admin#853]
### 描述问题 (Describe the problem)

buid项目的时候，报 (0 , import_theme.default) is not a function 错误
TypeError: (0 , import_theme.default) is not a function
    at getPluginsList (/application/vite.config.ts:496:30)
    at vite_config_default (/application/vite.config.ts:575:14)
    at loadConfigFromFile (file:///application/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:64317:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolveConfig (file:///application/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:63922:28)
    at async build (file:///application/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:46282:20)
    at async CAC.<anonymous> (file:///application/node_modules/vite/dist/node/cli.js:812:9)
[0mThe command '/bin/sh -c npm run build:${env}' returned a non-zero code: 1
Build step 'Execute shell' marked build as failure

### 如何复现该问题 (How to reproduce the problem)

npm run install后，再build

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
see https://github.com/pure-admin/vue-pure-admin/issues/852

**Comment by ggwork** [comment]
原因是pureadmin/theme 更新了，在build/plugins.ts文件中，原先引入pureadmin/theme的方式是
import themePreprocessorPlugin from "@pureadmin/theme";    
pureadmin/theme 更新后，这样引入vite就报错了。
应该加上大括号 ，或者回退@pureadmin/theme版本
import { themePreprocessorPlugin } from "@pureadmin/theme";

**Comment by xiaoxian521** [comment]
精简版不随便升级 `@pureadmin/theme` 因为它的最新版是随着vue-pure-admin来适应的，所以等2月底我们更新精简版再说吧
