### ISSUE TITLE
vite error

### ISSUE THREAD

**Issue by arb100** [pure-admin/vue-pure-admin#874]
### 描述问题 (Describe the problem)

jaki@jakis-MacBook-Pro dapdap-admin-front % pnpm dev

> fireboom-admin-web@4.4.0 dev /Users/jaki/Documents/work/dapdap-admin-front
> NODE_OPTIONS=--max-old-space-size=4096 vite

failed to load config from /Users/jaki/Documents/work/dapdap-admin-front/vite.config.ts
error when starting dev server:
TypeError: (0 , import_theme.default) is not a function
    at getPluginsList (/Users/jaki/Documents/work/dapdap-admin-front/vite.config.ts:532:30)
    at vite_config_default (/Users/jaki/Documents/work/dapdap-admin-front/vite.config.ts:629:14)
    at loadConfigFromFile (file:///Users/jaki/Documents/work/dapdap-admin-front/node_modules/.pnpm/vite@4.5.1_@types+node@20.11.5_sass@1.70.0_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66181:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (file:///Users/jaki/Documents/work/dapdap-admin-front/node_modules/.pnpm/vite@4.5.1_@types+node@20.11.5_sass@1.70.0_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-68d1a114.js:65774:28)
    at async _createServer (file:///Users/jaki/Documents/work/dapdap-admin-front/node_modules/.pnpm/vite@4.5.1_@types+node@20.11.5_sass@1.70.0_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-68d1a114.js:65051:20)
    at async CAC.<anonymous> (file:///Users/jaki/Documents/work/dapdap-admin-front/node_modules/.pnpm/vite@4.5.1_@types+node@20.11.5_sass@1.70.0_terser@5.27.0/node_modules/vite/dist/node/cli.js:763:24)
 ELIFECYCLE  Command failed with exit code 1.

### 如何复现该问题 (How to reproduce the problem)

pnpm dev

### 操作系统和浏览器信息 (Operating system and browser information)

mac,node v21.2.0

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
你这是精简版吧 把 [@pureadmin/theme](https://github.com/pure-admin/pure-admin-thin/blob/main/package.json#L62) 固定到`3.0.0`版本 等待`3`月份左右更新精简版
