### ISSUE TITLE
linux jenkins构建失败 pure-admin-thin version @4.5.0

### ISSUE THREAD

**Issue by a4825917** [pure-admin/vue-pure-admin#946]
### 描述问题 (Describe the problem)

<img width="1250" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/24914019/ebcd94b4-0f5e-4f80-b28b-5de2454a9adf">

failed to load config from /opt/server/jenkins/home/workspace/ones/pm-work-ui/vite.config.ts
error during build:
TypeError: (0 , import_theme.default) is not a function
    at getPluginsList (/opt/server/jenkins/home/workspace/ones/pm-work-ui/vite.config.ts:530:30)
    at vite_config_default (/opt/server/jenkins/home/workspace/ones/pm-work-ui/vite.config.ts:620:14)
    at loadConfigFromFile (file:///opt/server/jenkins/home/workspace/ones/pm-work-ui/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1_sass@1.63.6_terser@5.18.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64391:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolveConfig (file:///opt/server/jenkins/home/workspace/ones/pm-work-ui/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1_sass@1.63.6_terser@5.18.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63993:28)
    at async build (file:///opt/server/jenkins/home/workspace/ones/pm-work-ui/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1_sass@1.63.6_terser@5.18.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46318:20)
    at async CAC.<anonymous> (file:///opt/server/jenkins/home/workspace/ones/pm-work-ui/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1_sass@1.63.6_terser@5.18.1/node_modules/vite/dist/node/cli.js:812:9)
 ELIFECYCLE  Command failed with exit code 1.
Build step 'Execute shell' marked build as failure

以上是报错信息，本地node&pnpm版本和jenkins是一致的

### 如何复现该问题 (How to reproduce the problem)

linux jenkins 构建

node版本：16.14.0
pnpm 版本：8.12.1

### 操作系统和浏览器信息 (Operating system and browser information)

linux jenkins 构建

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
see https://github.com/pure-admin/vue-pure-admin/issues/853

**Comment by a4825917** [comment]
good
