### ISSUE TITLE
打包报错node 18.18.0

### ISSUE THREAD

**Issue by vuejsstudy** [pure-admin/vue-pure-admin#980]
### 描述问题 (Describe the problem)

error during build:
RollupError: Expression expected
    at getRollupError (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/parseAst.js:375:41)
    at ParseError.initialise (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:11155:28)
    at convertNode (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:12895:10)
    at convertProgram (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:12215:12)
    at Module.setSource (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:14039:24)
    at async ModuleLoader.addModuleSource (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:18689:13)
 ELIFECYCLE  Command failed with exit code 1.

### 如何复现该问题 (How to reproduce the problem)

error during build:
RollupError: Expression expected
    at getRollupError (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/parseAst.js:375:41)
    at ParseError.initialise (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:11155:28)
    at convertNode (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:12895:10)
    at convertProgram (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:12215:12)
    at Module.setSource (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:14039:24)
    at async ModuleLoader.addModuleSource (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:18689:13)
 ELIFECYCLE  Command failed with exit code 1.

### 操作系统和浏览器信息 (Operating system and browser information)

error during build:
RollupError: Expression expected
    at getRollupError (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/parseAst.js:375:41)
    at ParseError.initialise (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:11155:28)
    at convertNode (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:12895:10)
    at convertProgram (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:12215:12)
    at Module.setSource (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:14039:24)
    at async ModuleLoader.addModuleSource (file:///E:/%E9%A1%B9%E7%9B%AE/admin/node_modules/.pnpm/rollup@4.12.1/node_modules/rollup/dist/es/shared/node-entry.js:18689:13)
 ELIFECYCLE  Command failed with exit code 1.

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
用 20.11.1

**Comment by remember-5** [comment]
> 用 20.11.1

精简本v5.2.0，也出现这种错误，用 20.11.1无法解决报错
